Database:
  Type: postgres
  User: postgres
  Password: wangyi12358
  Host: 127.0.0.1
  Port: 5432
  Name: db_example
Kafka:
  Brokers:
    - 192.168.1.33:9192
  ClientId: go-zero-micro-client
  Consumer:
    Topics:
      - test_topic
    GroupId: go-zero-micro-group
CacheRedis:
  - Host: 192.168.1.33:6379
    Pass: fsdf.ds1.fdf8@5s-00
    Type: node